// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ngobrel.proto

package ngobrel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConversationType int32

const (
	ConversationType_PeerToPeer ConversationType = 0
	ConversationType_Group      ConversationType = 1
	ConversationType_Management ConversationType = 2
)

var ConversationType_name = map[int32]string{
	0: "PeerToPeer",
	1: "Group",
	2: "Management",
}
var ConversationType_value = map[string]int32{
	"PeerToPeer": 0,
	"Group":      1,
	"Management": 2,
}

func (x ConversationType) String() string {
	return proto.EnumName(ConversationType_name, int32(x))
}
func (ConversationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{0}
}

type MessageState int32

const (
	MessageState_Normal    MessageState = 0
	MessageState_Retracted MessageState = 1
)

var MessageState_name = map[int32]string{
	0: "Normal",
	1: "Retracted",
}
var MessageState_value = map[string]int32{
	"Normal":    0,
	"Retracted": 1,
}

func (x MessageState) String() string {
	return proto.EnumName(MessageState_name, int32(x))
}
func (MessageState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{1}
}

type MessageReceptionState int32

const (
	MessageReceptionState_Draft    MessageReceptionState = 0
	MessageReceptionState_Sent     MessageReceptionState = 1
	MessageReceptionState_Received MessageReceptionState = 2
	MessageReceptionState_Read     MessageReceptionState = 3
)

var MessageReceptionState_name = map[int32]string{
	0: "Draft",
	1: "Sent",
	2: "Received",
	3: "Read",
}
var MessageReceptionState_value = map[string]int32{
	"Draft":    0,
	"Sent":     1,
	"Received": 2,
	"Read":     3,
}

func (x MessageReceptionState) String() string {
	return proto.EnumName(MessageReceptionState_name, int32(x))
}
func (MessageReceptionState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{2}
}

type UploadMediaStatus int32

const (
	UploadMediaStatus_Uploading UploadMediaStatus = 0
	UploadMediaStatus_Done      UploadMediaStatus = 1
	UploadMediaStatus_Error     UploadMediaStatus = 2
)

var UploadMediaStatus_name = map[int32]string{
	0: "Uploading",
	1: "Done",
	2: "Error",
}
var UploadMediaStatus_value = map[string]int32{
	"Uploading": 0,
	"Done":      1,
	"Error":     2,
}

func (x UploadMediaStatus) String() string {
	return proto.EnumName(UploadMediaStatus_name, int32(x))
}
func (UploadMediaStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{3}
}

type EditProfileRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AvatarMediaId        string   `protobuf:"bytes,3,opt,name=avatarMediaId,proto3" json:"avatarMediaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileRequest) Reset()         { *m = EditProfileRequest{} }
func (m *EditProfileRequest) String() string { return proto.CompactTextString(m) }
func (*EditProfileRequest) ProtoMessage()    {}
func (*EditProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{0}
}
func (m *EditProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileRequest.Unmarshal(m, b)
}
func (m *EditProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileRequest.Marshal(b, m, deterministic)
}
func (dst *EditProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileRequest.Merge(dst, src)
}
func (m *EditProfileRequest) XXX_Size() int {
	return xxx_messageInfo_EditProfileRequest.Size(m)
}
func (m *EditProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileRequest proto.InternalMessageInfo

func (m *EditProfileRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EditProfileRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *EditProfileRequest) GetAvatarMediaId() string {
	if m != nil {
		return m.AvatarMediaId
	}
	return ""
}

type EditProfileResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditProfileResponse) Reset()         { *m = EditProfileResponse{} }
func (m *EditProfileResponse) String() string { return proto.CompactTextString(m) }
func (*EditProfileResponse) ProtoMessage()    {}
func (*EditProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{1}
}
func (m *EditProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditProfileResponse.Unmarshal(m, b)
}
func (m *EditProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditProfileResponse.Marshal(b, m, deterministic)
}
func (dst *EditProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditProfileResponse.Merge(dst, src)
}
func (m *EditProfileResponse) XXX_Size() int {
	return xxx_messageInfo_EditProfileResponse.Size(m)
}
func (m *EditProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditProfileResponse proto.InternalMessageInfo

func (m *EditProfileResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *EditProfileResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetProfileRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileRequest) Reset()         { *m = GetProfileRequest{} }
func (m *GetProfileRequest) String() string { return proto.CompactTextString(m) }
func (*GetProfileRequest) ProtoMessage()    {}
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{2}
}
func (m *GetProfileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileRequest.Unmarshal(m, b)
}
func (m *GetProfileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileRequest.Marshal(b, m, deterministic)
}
func (dst *GetProfileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileRequest.Merge(dst, src)
}
func (m *GetProfileRequest) XXX_Size() int {
	return xxx_messageInfo_GetProfileRequest.Size(m)
}
func (m *GetProfileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileRequest proto.InternalMessageInfo

func (m *GetProfileRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type GetProfileResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AvatarMediaId        string   `protobuf:"bytes,3,opt,name=avatarMediaId,proto3" json:"avatarMediaId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProfileResponse) Reset()         { *m = GetProfileResponse{} }
func (m *GetProfileResponse) String() string { return proto.CompactTextString(m) }
func (*GetProfileResponse) ProtoMessage()    {}
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{3}
}
func (m *GetProfileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProfileResponse.Unmarshal(m, b)
}
func (m *GetProfileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProfileResponse.Marshal(b, m, deterministic)
}
func (dst *GetProfileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProfileResponse.Merge(dst, src)
}
func (m *GetProfileResponse) XXX_Size() int {
	return xxx_messageInfo_GetProfileResponse.Size(m)
}
func (m *GetProfileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProfileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetProfileResponse proto.InternalMessageInfo

func (m *GetProfileResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetProfileResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetProfileResponse) GetAvatarMediaId() string {
	if m != nil {
		return m.AvatarMediaId
	}
	return ""
}

type ListConversationsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListConversationsRequest) Reset()         { *m = ListConversationsRequest{} }
func (m *ListConversationsRequest) String() string { return proto.CompactTextString(m) }
func (*ListConversationsRequest) ProtoMessage()    {}
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{4}
}
func (m *ListConversationsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConversationsRequest.Unmarshal(m, b)
}
func (m *ListConversationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConversationsRequest.Marshal(b, m, deterministic)
}
func (dst *ListConversationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConversationsRequest.Merge(dst, src)
}
func (m *ListConversationsRequest) XXX_Size() int {
	return xxx_messageInfo_ListConversationsRequest.Size(m)
}
func (m *ListConversationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConversationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListConversationsRequest proto.InternalMessageInfo

type ListConversationsResponse struct {
	List                 []*Conversations `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListConversationsResponse) Reset()         { *m = ListConversationsResponse{} }
func (m *ListConversationsResponse) String() string { return proto.CompactTextString(m) }
func (*ListConversationsResponse) ProtoMessage()    {}
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{5}
}
func (m *ListConversationsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListConversationsResponse.Unmarshal(m, b)
}
func (m *ListConversationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListConversationsResponse.Marshal(b, m, deterministic)
}
func (dst *ListConversationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListConversationsResponse.Merge(dst, src)
}
func (m *ListConversationsResponse) XXX_Size() int {
	return xxx_messageInfo_ListConversationsResponse.Size(m)
}
func (m *ListConversationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListConversationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListConversationsResponse proto.InternalMessageInfo

func (m *ListConversationsResponse) GetList() []*Conversations {
	if m != nil {
		return m.List
	}
	return nil
}

type Conversations struct {
	ChatID               string   `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	ChatName             string   `protobuf:"bytes,2,opt,name=chatName,proto3" json:"chatName,omitempty"`
	Excerpt              string   `protobuf:"bytes,3,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Notification         int64    `protobuf:"varint,5,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Conversations) Reset()         { *m = Conversations{} }
func (m *Conversations) String() string { return proto.CompactTextString(m) }
func (*Conversations) ProtoMessage()    {}
func (*Conversations) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{6}
}
func (m *Conversations) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Conversations.Unmarshal(m, b)
}
func (m *Conversations) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Conversations.Marshal(b, m, deterministic)
}
func (dst *Conversations) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Conversations.Merge(dst, src)
}
func (m *Conversations) XXX_Size() int {
	return xxx_messageInfo_Conversations.Size(m)
}
func (m *Conversations) XXX_DiscardUnknown() {
	xxx_messageInfo_Conversations.DiscardUnknown(m)
}

var xxx_messageInfo_Conversations proto.InternalMessageInfo

func (m *Conversations) GetChatID() string {
	if m != nil {
		return m.ChatID
	}
	return ""
}

func (m *Conversations) GetChatName() string {
	if m != nil {
		return m.ChatName
	}
	return ""
}

func (m *Conversations) GetExcerpt() string {
	if m != nil {
		return m.Excerpt
	}
	return ""
}

func (m *Conversations) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Conversations) GetNotification() int64 {
	if m != nil {
		return m.Notification
	}
	return 0
}

type UpdateConversationRequest struct {
	ChatID               string   `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	Excerpt              string   `protobuf:"bytes,2,opt,name=excerpt,proto3" json:"excerpt,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConversationRequest) Reset()         { *m = UpdateConversationRequest{} }
func (m *UpdateConversationRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationRequest) ProtoMessage()    {}
func (*UpdateConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{7}
}
func (m *UpdateConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationRequest.Unmarshal(m, b)
}
func (m *UpdateConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationRequest.Merge(dst, src)
}
func (m *UpdateConversationRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationRequest.Size(m)
}
func (m *UpdateConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationRequest proto.InternalMessageInfo

func (m *UpdateConversationRequest) GetChatID() string {
	if m != nil {
		return m.ChatID
	}
	return ""
}

func (m *UpdateConversationRequest) GetExcerpt() string {
	if m != nil {
		return m.Excerpt
	}
	return ""
}

func (m *UpdateConversationRequest) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type UpdateConversationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConversationResponse) Reset()         { *m = UpdateConversationResponse{} }
func (m *UpdateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateConversationResponse) ProtoMessage()    {}
func (*UpdateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{8}
}
func (m *UpdateConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConversationResponse.Unmarshal(m, b)
}
func (m *UpdateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConversationResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConversationResponse.Merge(dst, src)
}
func (m *UpdateConversationResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateConversationResponse.Size(m)
}
func (m *UpdateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConversationResponse proto.InternalMessageInfo

func (m *UpdateConversationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *UpdateConversationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteContactRequest struct {
	// userID @ metadata
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContactRequest) Reset()         { *m = DeleteContactRequest{} }
func (m *DeleteContactRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContactRequest) ProtoMessage()    {}
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{9}
}
func (m *DeleteContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContactRequest.Unmarshal(m, b)
}
func (m *DeleteContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContactRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContactRequest.Merge(dst, src)
}
func (m *DeleteContactRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContactRequest.Size(m)
}
func (m *DeleteContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContactRequest proto.InternalMessageInfo

func (m *DeleteContactRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type DeleteContactResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContactResponse) Reset()         { *m = DeleteContactResponse{} }
func (m *DeleteContactResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteContactResponse) ProtoMessage()    {}
func (*DeleteContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{10}
}
func (m *DeleteContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContactResponse.Unmarshal(m, b)
}
func (m *DeleteContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContactResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContactResponse.Merge(dst, src)
}
func (m *DeleteContactResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteContactResponse.Size(m)
}
func (m *DeleteContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContactResponse proto.InternalMessageInfo

func (m *DeleteContactResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteContactResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetContactsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactsRequest) Reset()         { *m = GetContactsRequest{} }
func (m *GetContactsRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactsRequest) ProtoMessage()    {}
func (*GetContactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{11}
}
func (m *GetContactsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactsRequest.Unmarshal(m, b)
}
func (m *GetContactsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactsRequest.Marshal(b, m, deterministic)
}
func (dst *GetContactsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactsRequest.Merge(dst, src)
}
func (m *GetContactsRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactsRequest.Size(m)
}
func (m *GetContactsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactsRequest proto.InternalMessageInfo

type GetContactsResponse struct {
	List                 []*Contacts `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetContactsResponse) Reset()         { *m = GetContactsResponse{} }
func (m *GetContactsResponse) String() string { return proto.CompactTextString(m) }
func (*GetContactsResponse) ProtoMessage()    {}
func (*GetContactsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{12}
}
func (m *GetContactsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactsResponse.Unmarshal(m, b)
}
func (m *GetContactsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactsResponse.Marshal(b, m, deterministic)
}
func (dst *GetContactsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactsResponse.Merge(dst, src)
}
func (m *GetContactsResponse) XXX_Size() int {
	return xxx_messageInfo_GetContactsResponse.Size(m)
}
func (m *GetContactsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactsResponse proto.InternalMessageInfo

func (m *GetContactsResponse) GetList() []*Contacts {
	if m != nil {
		return m.List
	}
	return nil
}

type Contacts struct {
	PeerID               string   `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Notification         int64    `protobuf:"varint,3,opt,name=notification,proto3" json:"notification,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Contacts) Reset()         { *m = Contacts{} }
func (m *Contacts) String() string { return proto.CompactTextString(m) }
func (*Contacts) ProtoMessage()    {}
func (*Contacts) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{13}
}
func (m *Contacts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contacts.Unmarshal(m, b)
}
func (m *Contacts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contacts.Marshal(b, m, deterministic)
}
func (dst *Contacts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contacts.Merge(dst, src)
}
func (m *Contacts) XXX_Size() int {
	return xxx_messageInfo_Contacts.Size(m)
}
func (m *Contacts) XXX_DiscardUnknown() {
	xxx_messageInfo_Contacts.DiscardUnknown(m)
}

var xxx_messageInfo_Contacts proto.InternalMessageInfo

func (m *Contacts) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *Contacts) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contacts) GetNotification() int64 {
	if m != nil {
		return m.Notification
	}
	return 0
}

type PutContactRequest struct {
	ContactData          *Contacts `protobuf:"bytes,2,opt,name=contactData,proto3" json:"contactData,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PutContactRequest) Reset()         { *m = PutContactRequest{} }
func (m *PutContactRequest) String() string { return proto.CompactTextString(m) }
func (*PutContactRequest) ProtoMessage()    {}
func (*PutContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{14}
}
func (m *PutContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutContactRequest.Unmarshal(m, b)
}
func (m *PutContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutContactRequest.Marshal(b, m, deterministic)
}
func (dst *PutContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutContactRequest.Merge(dst, src)
}
func (m *PutContactRequest) XXX_Size() int {
	return xxx_messageInfo_PutContactRequest.Size(m)
}
func (m *PutContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutContactRequest proto.InternalMessageInfo

func (m *PutContactRequest) GetContactData() *Contacts {
	if m != nil {
		return m.ContactData
	}
	return nil
}

type PutContactResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutContactResponse) Reset()         { *m = PutContactResponse{} }
func (m *PutContactResponse) String() string { return proto.CompactTextString(m) }
func (*PutContactResponse) ProtoMessage()    {}
func (*PutContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{15}
}
func (m *PutContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutContactResponse.Unmarshal(m, b)
}
func (m *PutContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutContactResponse.Marshal(b, m, deterministic)
}
func (dst *PutContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutContactResponse.Merge(dst, src)
}
func (m *PutContactResponse) XXX_Size() int {
	return xxx_messageInfo_PutContactResponse.Size(m)
}
func (m *PutContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutContactResponse proto.InternalMessageInfo

func (m *PutContactResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PutContactResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetMessageReceptionStateRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	MessageID            string   `protobuf:"bytes,2,opt,name=messageID,proto3" json:"messageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageReceptionStateRequest) Reset()         { *m = GetMessageReceptionStateRequest{} }
func (m *GetMessageReceptionStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessageReceptionStateRequest) ProtoMessage()    {}
func (*GetMessageReceptionStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{16}
}
func (m *GetMessageReceptionStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageReceptionStateRequest.Unmarshal(m, b)
}
func (m *GetMessageReceptionStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageReceptionStateRequest.Marshal(b, m, deterministic)
}
func (dst *GetMessageReceptionStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageReceptionStateRequest.Merge(dst, src)
}
func (m *GetMessageReceptionStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessageReceptionStateRequest.Size(m)
}
func (m *GetMessageReceptionStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageReceptionStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageReceptionStateRequest proto.InternalMessageInfo

func (m *GetMessageReceptionStateRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetMessageReceptionStateRequest) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

type GetMessageReceptionStateResponse struct {
	Status               MessageReceptionState `protobuf:"varint,1,opt,name=status,proto3,enum=MessageReceptionState" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *GetMessageReceptionStateResponse) Reset()         { *m = GetMessageReceptionStateResponse{} }
func (m *GetMessageReceptionStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessageReceptionStateResponse) ProtoMessage()    {}
func (*GetMessageReceptionStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{17}
}
func (m *GetMessageReceptionStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageReceptionStateResponse.Unmarshal(m, b)
}
func (m *GetMessageReceptionStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageReceptionStateResponse.Marshal(b, m, deterministic)
}
func (dst *GetMessageReceptionStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageReceptionStateResponse.Merge(dst, src)
}
func (m *GetMessageReceptionStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessageReceptionStateResponse.Size(m)
}
func (m *GetMessageReceptionStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageReceptionStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageReceptionStateResponse proto.InternalMessageInfo

func (m *GetMessageReceptionStateResponse) GetStatus() MessageReceptionState {
	if m != nil {
		return m.Status
	}
	return MessageReceptionState_Draft
}

type GetMessageStateRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	MessageID            string   `protobuf:"bytes,2,opt,name=messageID,proto3" json:"messageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessageStateRequest) Reset()         { *m = GetMessageStateRequest{} }
func (m *GetMessageStateRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessageStateRequest) ProtoMessage()    {}
func (*GetMessageStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{18}
}
func (m *GetMessageStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageStateRequest.Unmarshal(m, b)
}
func (m *GetMessageStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageStateRequest.Marshal(b, m, deterministic)
}
func (dst *GetMessageStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageStateRequest.Merge(dst, src)
}
func (m *GetMessageStateRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessageStateRequest.Size(m)
}
func (m *GetMessageStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageStateRequest proto.InternalMessageInfo

func (m *GetMessageStateRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetMessageStateRequest) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

type GetMessageStateResponse struct {
	State                MessageState `protobuf:"varint,1,opt,name=state,proto3,enum=MessageState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMessageStateResponse) Reset()         { *m = GetMessageStateResponse{} }
func (m *GetMessageStateResponse) String() string { return proto.CompactTextString(m) }
func (*GetMessageStateResponse) ProtoMessage()    {}
func (*GetMessageStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{19}
}
func (m *GetMessageStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessageStateResponse.Unmarshal(m, b)
}
func (m *GetMessageStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessageStateResponse.Marshal(b, m, deterministic)
}
func (dst *GetMessageStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessageStateResponse.Merge(dst, src)
}
func (m *GetMessageStateResponse) XXX_Size() int {
	return xxx_messageInfo_GetMessageStateResponse.Size(m)
}
func (m *GetMessageStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessageStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessageStateResponse proto.InternalMessageInfo

func (m *GetMessageStateResponse) GetState() MessageState {
	if m != nil {
		return m.State
	}
	return MessageState_Normal
}

type PutMessageStateRequest struct {
	MessageID            string                `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	Status               MessageReceptionState `protobuf:"varint,2,opt,name=status,proto3,enum=MessageReceptionState" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PutMessageStateRequest) Reset()         { *m = PutMessageStateRequest{} }
func (m *PutMessageStateRequest) String() string { return proto.CompactTextString(m) }
func (*PutMessageStateRequest) ProtoMessage()    {}
func (*PutMessageStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{20}
}
func (m *PutMessageStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMessageStateRequest.Unmarshal(m, b)
}
func (m *PutMessageStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMessageStateRequest.Marshal(b, m, deterministic)
}
func (dst *PutMessageStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMessageStateRequest.Merge(dst, src)
}
func (m *PutMessageStateRequest) XXX_Size() int {
	return xxx_messageInfo_PutMessageStateRequest.Size(m)
}
func (m *PutMessageStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMessageStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMessageStateRequest proto.InternalMessageInfo

func (m *PutMessageStateRequest) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *PutMessageStateRequest) GetStatus() MessageReceptionState {
	if m != nil {
		return m.Status
	}
	return MessageReceptionState_Draft
}

type PutMessageStateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutMessageStateResponse) Reset()         { *m = PutMessageStateResponse{} }
func (m *PutMessageStateResponse) String() string { return proto.CompactTextString(m) }
func (*PutMessageStateResponse) ProtoMessage()    {}
func (*PutMessageStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{21}
}
func (m *PutMessageStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMessageStateResponse.Unmarshal(m, b)
}
func (m *PutMessageStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMessageStateResponse.Marshal(b, m, deterministic)
}
func (dst *PutMessageStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMessageStateResponse.Merge(dst, src)
}
func (m *PutMessageStateResponse) XXX_Size() int {
	return xxx_messageInfo_PutMessageStateResponse.Size(m)
}
func (m *PutMessageStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMessageStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutMessageStateResponse proto.InternalMessageInfo

func (m *PutMessageStateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PutMessageStateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PutMessageReceptionStateRequest struct {
	// userID is fetched from metadata
	MessageID            string                `protobuf:"bytes,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	Status               MessageReceptionState `protobuf:"varint,2,opt,name=status,proto3,enum=MessageReceptionState" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PutMessageReceptionStateRequest) Reset()         { *m = PutMessageReceptionStateRequest{} }
func (m *PutMessageReceptionStateRequest) String() string { return proto.CompactTextString(m) }
func (*PutMessageReceptionStateRequest) ProtoMessage()    {}
func (*PutMessageReceptionStateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{22}
}
func (m *PutMessageReceptionStateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMessageReceptionStateRequest.Unmarshal(m, b)
}
func (m *PutMessageReceptionStateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMessageReceptionStateRequest.Marshal(b, m, deterministic)
}
func (dst *PutMessageReceptionStateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMessageReceptionStateRequest.Merge(dst, src)
}
func (m *PutMessageReceptionStateRequest) XXX_Size() int {
	return xxx_messageInfo_PutMessageReceptionStateRequest.Size(m)
}
func (m *PutMessageReceptionStateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMessageReceptionStateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMessageReceptionStateRequest proto.InternalMessageInfo

func (m *PutMessageReceptionStateRequest) GetMessageID() string {
	if m != nil {
		return m.MessageID
	}
	return ""
}

func (m *PutMessageReceptionStateRequest) GetStatus() MessageReceptionState {
	if m != nil {
		return m.Status
	}
	return MessageReceptionState_Draft
}

type PutMessageReceptionStateResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutMessageReceptionStateResponse) Reset()         { *m = PutMessageReceptionStateResponse{} }
func (m *PutMessageReceptionStateResponse) String() string { return proto.CompactTextString(m) }
func (*PutMessageReceptionStateResponse) ProtoMessage()    {}
func (*PutMessageReceptionStateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{23}
}
func (m *PutMessageReceptionStateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMessageReceptionStateResponse.Unmarshal(m, b)
}
func (m *PutMessageReceptionStateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMessageReceptionStateResponse.Marshal(b, m, deterministic)
}
func (dst *PutMessageReceptionStateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMessageReceptionStateResponse.Merge(dst, src)
}
func (m *PutMessageReceptionStateResponse) XXX_Size() int {
	return xxx_messageInfo_PutMessageReceptionStateResponse.Size(m)
}
func (m *PutMessageReceptionStateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMessageReceptionStateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutMessageReceptionStateResponse proto.InternalMessageInfo

func (m *PutMessageReceptionStateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CreateConversationRequest struct {
	UserID               string           `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ChatID               string           `protobuf:"bytes,2,opt,name=chatID,proto3" json:"chatID,omitempty"`
	Type                 ConversationType `protobuf:"varint,3,opt,name=type,proto3,enum=ConversationType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateConversationRequest) Reset()         { *m = CreateConversationRequest{} }
func (m *CreateConversationRequest) String() string { return proto.CompactTextString(m) }
func (*CreateConversationRequest) ProtoMessage()    {}
func (*CreateConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{24}
}
func (m *CreateConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationRequest.Unmarshal(m, b)
}
func (m *CreateConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationRequest.Marshal(b, m, deterministic)
}
func (dst *CreateConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationRequest.Merge(dst, src)
}
func (m *CreateConversationRequest) XXX_Size() int {
	return xxx_messageInfo_CreateConversationRequest.Size(m)
}
func (m *CreateConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationRequest proto.InternalMessageInfo

func (m *CreateConversationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *CreateConversationRequest) GetChatID() string {
	if m != nil {
		return m.ChatID
	}
	return ""
}

func (m *CreateConversationRequest) GetType() ConversationType {
	if m != nil {
		return m.Type
	}
	return ConversationType_PeerToPeer
}

type CreateConversationResponse struct {
	ChatID               string   `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateConversationResponse) Reset()         { *m = CreateConversationResponse{} }
func (m *CreateConversationResponse) String() string { return proto.CompactTextString(m) }
func (*CreateConversationResponse) ProtoMessage()    {}
func (*CreateConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{25}
}
func (m *CreateConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConversationResponse.Unmarshal(m, b)
}
func (m *CreateConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConversationResponse.Marshal(b, m, deterministic)
}
func (dst *CreateConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConversationResponse.Merge(dst, src)
}
func (m *CreateConversationResponse) XXX_Size() int {
	return xxx_messageInfo_CreateConversationResponse.Size(m)
}
func (m *CreateConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConversationResponse proto.InternalMessageInfo

func (m *CreateConversationResponse) GetChatID() string {
	if m != nil {
		return m.ChatID
	}
	return ""
}

func (m *CreateConversationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteConversationRequest struct {
	ChatID               string   `protobuf:"bytes,1,opt,name=chatID,proto3" json:"chatID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConversationRequest) Reset()         { *m = DeleteConversationRequest{} }
func (m *DeleteConversationRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteConversationRequest) ProtoMessage()    {}
func (*DeleteConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{26}
}
func (m *DeleteConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConversationRequest.Unmarshal(m, b)
}
func (m *DeleteConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConversationRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConversationRequest.Merge(dst, src)
}
func (m *DeleteConversationRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteConversationRequest.Size(m)
}
func (m *DeleteConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConversationRequest proto.InternalMessageInfo

func (m *DeleteConversationRequest) GetChatID() string {
	if m != nil {
		return m.ChatID
	}
	return ""
}

type DeleteConversationResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteConversationResponse) Reset()         { *m = DeleteConversationResponse{} }
func (m *DeleteConversationResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteConversationResponse) ProtoMessage()    {}
func (*DeleteConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{27}
}
func (m *DeleteConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteConversationResponse.Unmarshal(m, b)
}
func (m *DeleteConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteConversationResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteConversationResponse.Merge(dst, src)
}
func (m *DeleteConversationResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteConversationResponse.Size(m)
}
func (m *DeleteConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteConversationResponse proto.InternalMessageInfo

func (m *DeleteConversationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteConversationResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type PutIntoConversationRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ConversationID       string   `protobuf:"bytes,2,opt,name=conversationID,proto3" json:"conversationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutIntoConversationRequest) Reset()         { *m = PutIntoConversationRequest{} }
func (m *PutIntoConversationRequest) String() string { return proto.CompactTextString(m) }
func (*PutIntoConversationRequest) ProtoMessage()    {}
func (*PutIntoConversationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{28}
}
func (m *PutIntoConversationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutIntoConversationRequest.Unmarshal(m, b)
}
func (m *PutIntoConversationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutIntoConversationRequest.Marshal(b, m, deterministic)
}
func (dst *PutIntoConversationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutIntoConversationRequest.Merge(dst, src)
}
func (m *PutIntoConversationRequest) XXX_Size() int {
	return xxx_messageInfo_PutIntoConversationRequest.Size(m)
}
func (m *PutIntoConversationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutIntoConversationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutIntoConversationRequest proto.InternalMessageInfo

func (m *PutIntoConversationRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PutIntoConversationRequest) GetConversationID() string {
	if m != nil {
		return m.ConversationID
	}
	return ""
}

type PutIntoConversationResponse struct {
	ConversationID       string   `protobuf:"bytes,1,opt,name=conversationID,proto3" json:"conversationID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutIntoConversationResponse) Reset()         { *m = PutIntoConversationResponse{} }
func (m *PutIntoConversationResponse) String() string { return proto.CompactTextString(m) }
func (*PutIntoConversationResponse) ProtoMessage()    {}
func (*PutIntoConversationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{29}
}
func (m *PutIntoConversationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutIntoConversationResponse.Unmarshal(m, b)
}
func (m *PutIntoConversationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutIntoConversationResponse.Marshal(b, m, deterministic)
}
func (dst *PutIntoConversationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutIntoConversationResponse.Merge(dst, src)
}
func (m *PutIntoConversationResponse) XXX_Size() int {
	return xxx_messageInfo_PutIntoConversationResponse.Size(m)
}
func (m *PutIntoConversationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutIntoConversationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutIntoConversationResponse proto.InternalMessageInfo

func (m *PutIntoConversationResponse) GetConversationID() string {
	if m != nil {
		return m.ConversationID
	}
	return ""
}

type UploadMediaRequest struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadMediaRequest) Reset()         { *m = UploadMediaRequest{} }
func (m *UploadMediaRequest) String() string { return proto.CompactTextString(m) }
func (*UploadMediaRequest) ProtoMessage()    {}
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{30}
}
func (m *UploadMediaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadMediaRequest.Unmarshal(m, b)
}
func (m *UploadMediaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadMediaRequest.Marshal(b, m, deterministic)
}
func (dst *UploadMediaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadMediaRequest.Merge(dst, src)
}
func (m *UploadMediaRequest) XXX_Size() int {
	return xxx_messageInfo_UploadMediaRequest.Size(m)
}
func (m *UploadMediaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadMediaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UploadMediaRequest proto.InternalMessageInfo

func (m *UploadMediaRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type UploadMediaResponse struct {
	MediaID              string            `protobuf:"bytes,1,opt,name=mediaID,proto3" json:"mediaID,omitempty"`
	Status               UploadMediaStatus `protobuf:"varint,2,opt,name=status,proto3,enum=UploadMediaStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *UploadMediaResponse) Reset()         { *m = UploadMediaResponse{} }
func (m *UploadMediaResponse) String() string { return proto.CompactTextString(m) }
func (*UploadMediaResponse) ProtoMessage()    {}
func (*UploadMediaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{31}
}
func (m *UploadMediaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadMediaResponse.Unmarshal(m, b)
}
func (m *UploadMediaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadMediaResponse.Marshal(b, m, deterministic)
}
func (dst *UploadMediaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadMediaResponse.Merge(dst, src)
}
func (m *UploadMediaResponse) XXX_Size() int {
	return xxx_messageInfo_UploadMediaResponse.Size(m)
}
func (m *UploadMediaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadMediaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UploadMediaResponse proto.InternalMessageInfo

func (m *UploadMediaResponse) GetMediaID() string {
	if m != nil {
		return m.MediaID
	}
	return ""
}

func (m *UploadMediaResponse) GetStatus() UploadMediaStatus {
	if m != nil {
		return m.Status
	}
	return UploadMediaStatus_Uploading
}

type GetMediaRequest struct {
	MediaID              string   `protobuf:"bytes,1,opt,name=mediaID,proto3" json:"mediaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMediaRequest) Reset()         { *m = GetMediaRequest{} }
func (m *GetMediaRequest) String() string { return proto.CompactTextString(m) }
func (*GetMediaRequest) ProtoMessage()    {}
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{32}
}
func (m *GetMediaRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMediaRequest.Unmarshal(m, b)
}
func (m *GetMediaRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMediaRequest.Marshal(b, m, deterministic)
}
func (dst *GetMediaRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMediaRequest.Merge(dst, src)
}
func (m *GetMediaRequest) XXX_Size() int {
	return xxx_messageInfo_GetMediaRequest.Size(m)
}
func (m *GetMediaRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMediaRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMediaRequest proto.InternalMessageInfo

func (m *GetMediaRequest) GetMediaID() string {
	if m != nil {
		return m.MediaID
	}
	return ""
}

type GetMediaResponse struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMediaResponse) Reset()         { *m = GetMediaResponse{} }
func (m *GetMediaResponse) String() string { return proto.CompactTextString(m) }
func (*GetMediaResponse) ProtoMessage()    {}
func (*GetMediaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{33}
}
func (m *GetMediaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMediaResponse.Unmarshal(m, b)
}
func (m *GetMediaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMediaResponse.Marshal(b, m, deterministic)
}
func (dst *GetMediaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMediaResponse.Merge(dst, src)
}
func (m *GetMediaResponse) XXX_Size() int {
	return xxx_messageInfo_GetMediaResponse.Size(m)
}
func (m *GetMediaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMediaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMediaResponse proto.InternalMessageInfo

func (m *GetMediaResponse) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type GetMessagesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesRequest) Reset()         { *m = GetMessagesRequest{} }
func (m *GetMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*GetMessagesRequest) ProtoMessage()    {}
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{34}
}
func (m *GetMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesRequest.Unmarshal(m, b)
}
func (m *GetMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesRequest.Marshal(b, m, deterministic)
}
func (dst *GetMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesRequest.Merge(dst, src)
}
func (m *GetMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_GetMessagesRequest.Size(m)
}
func (m *GetMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesRequest proto.InternalMessageInfo

type GetMessagesResponseItem struct {
	RecipientID          string   `protobuf:"bytes,1,opt,name=recipientID,proto3" json:"recipientID,omitempty"`
	SenderID             string   `protobuf:"bytes,2,opt,name=senderID,proto3" json:"senderID,omitempty"`
	SenderDeviceID       string   `protobuf:"bytes,3,opt,name=senderDeviceID,proto3" json:"senderDeviceID,omitempty"`
	MessageID            int64    `protobuf:"varint,4,opt,name=messageID,proto3" json:"messageID,omitempty"`
	MessageTimestamp     int64    `protobuf:"varint,5,opt,name=messageTimestamp,proto3" json:"messageTimestamp,omitempty"`
	MessageContents      string   `protobuf:"bytes,6,opt,name=messageContents,proto3" json:"messageContents,omitempty"`
	MessageEncrypted     bool     `protobuf:"varint,7,opt,name=messageEncrypted,proto3" json:"messageEncrypted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMessagesResponseItem) Reset()         { *m = GetMessagesResponseItem{} }
func (m *GetMessagesResponseItem) String() string { return proto.CompactTextString(m) }
func (*GetMessagesResponseItem) ProtoMessage()    {}
func (*GetMessagesResponseItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{35}
}
func (m *GetMessagesResponseItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMessagesResponseItem.Unmarshal(m, b)
}
func (m *GetMessagesResponseItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMessagesResponseItem.Marshal(b, m, deterministic)
}
func (dst *GetMessagesResponseItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMessagesResponseItem.Merge(dst, src)
}
func (m *GetMessagesResponseItem) XXX_Size() int {
	return xxx_messageInfo_GetMessagesResponseItem.Size(m)
}
func (m *GetMessagesResponseItem) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMessagesResponseItem.DiscardUnknown(m)
}

var xxx_messageInfo_GetMessagesResponseItem proto.InternalMessageInfo

func (m *GetMessagesResponseItem) GetRecipientID() string {
	if m != nil {
		return m.RecipientID
	}
	return ""
}

func (m *GetMessagesResponseItem) GetSenderID() string {
	if m != nil {
		return m.SenderID
	}
	return ""
}

func (m *GetMessagesResponseItem) GetSenderDeviceID() string {
	if m != nil {
		return m.SenderDeviceID
	}
	return ""
}

func (m *GetMessagesResponseItem) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *GetMessagesResponseItem) GetMessageTimestamp() int64 {
	if m != nil {
		return m.MessageTimestamp
	}
	return 0
}

func (m *GetMessagesResponseItem) GetMessageContents() string {
	if m != nil {
		return m.MessageContents
	}
	return ""
}

func (m *GetMessagesResponseItem) GetMessageEncrypted() bool {
	if m != nil {
		return m.MessageEncrypted
	}
	return false
}

type PutMessageResponse struct {
	MessageID            int64    `protobuf:"varint,1,opt,name=messageID,proto3" json:"messageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutMessageResponse) Reset()         { *m = PutMessageResponse{} }
func (m *PutMessageResponse) String() string { return proto.CompactTextString(m) }
func (*PutMessageResponse) ProtoMessage()    {}
func (*PutMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{36}
}
func (m *PutMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMessageResponse.Unmarshal(m, b)
}
func (m *PutMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMessageResponse.Marshal(b, m, deterministic)
}
func (dst *PutMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMessageResponse.Merge(dst, src)
}
func (m *PutMessageResponse) XXX_Size() int {
	return xxx_messageInfo_PutMessageResponse.Size(m)
}
func (m *PutMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutMessageResponse proto.InternalMessageInfo

func (m *PutMessageResponse) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

type PutMessageRequest struct {
	RecipientID          string   `protobuf:"bytes,1,opt,name=recipientID,proto3" json:"recipientID,omitempty"`
	MessageID            int64    `protobuf:"varint,2,opt,name=messageID,proto3" json:"messageID,omitempty"`
	MessageTimestamp     int64    `protobuf:"varint,3,opt,name=messageTimestamp,proto3" json:"messageTimestamp,omitempty"`
	MessageContents      string   `protobuf:"bytes,4,opt,name=messageContents,proto3" json:"messageContents,omitempty"`
	MessageEncrypted     bool     `protobuf:"varint,5,opt,name=messageEncrypted,proto3" json:"messageEncrypted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutMessageRequest) Reset()         { *m = PutMessageRequest{} }
func (m *PutMessageRequest) String() string { return proto.CompactTextString(m) }
func (*PutMessageRequest) ProtoMessage()    {}
func (*PutMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{37}
}
func (m *PutMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutMessageRequest.Unmarshal(m, b)
}
func (m *PutMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutMessageRequest.Marshal(b, m, deterministic)
}
func (dst *PutMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutMessageRequest.Merge(dst, src)
}
func (m *PutMessageRequest) XXX_Size() int {
	return xxx_messageInfo_PutMessageRequest.Size(m)
}
func (m *PutMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutMessageRequest proto.InternalMessageInfo

func (m *PutMessageRequest) GetRecipientID() string {
	if m != nil {
		return m.RecipientID
	}
	return ""
}

func (m *PutMessageRequest) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *PutMessageRequest) GetMessageTimestamp() int64 {
	if m != nil {
		return m.MessageTimestamp
	}
	return 0
}

func (m *PutMessageRequest) GetMessageContents() string {
	if m != nil {
		return m.MessageContents
	}
	return ""
}

func (m *PutMessageRequest) GetMessageEncrypted() bool {
	if m != nil {
		return m.MessageEncrypted
	}
	return false
}

type PublicGetKeysRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicGetKeysRequest) Reset()         { *m = PublicGetKeysRequest{} }
func (m *PublicGetKeysRequest) String() string { return proto.CompactTextString(m) }
func (*PublicGetKeysRequest) ProtoMessage()    {}
func (*PublicGetKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{38}
}
func (m *PublicGetKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicGetKeysRequest.Unmarshal(m, b)
}
func (m *PublicGetKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicGetKeysRequest.Marshal(b, m, deterministic)
}
func (dst *PublicGetKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicGetKeysRequest.Merge(dst, src)
}
func (m *PublicGetKeysRequest) XXX_Size() int {
	return xxx_messageInfo_PublicGetKeysRequest.Size(m)
}
func (m *PublicGetKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicGetKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicGetKeysRequest proto.InternalMessageInfo

func (m *PublicGetKeysRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type PublicGetKeysResponse struct {
	Keys                 []byte   `protobuf:"bytes,1,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicGetKeysResponse) Reset()         { *m = PublicGetKeysResponse{} }
func (m *PublicGetKeysResponse) String() string { return proto.CompactTextString(m) }
func (*PublicGetKeysResponse) ProtoMessage()    {}
func (*PublicGetKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{39}
}
func (m *PublicGetKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicGetKeysResponse.Unmarshal(m, b)
}
func (m *PublicGetKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicGetKeysResponse.Marshal(b, m, deterministic)
}
func (dst *PublicGetKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicGetKeysResponse.Merge(dst, src)
}
func (m *PublicGetKeysResponse) XXX_Size() int {
	return xxx_messageInfo_PublicGetKeysResponse.Size(m)
}
func (m *PublicGetKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicGetKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicGetKeysResponse proto.InternalMessageInfo

func (m *PublicGetKeysResponse) GetKeys() []byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type PutKeysRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Keys                 []byte   `protobuf:"bytes,2,opt,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutKeysRequest) Reset()         { *m = PutKeysRequest{} }
func (m *PutKeysRequest) String() string { return proto.CompactTextString(m) }
func (*PutKeysRequest) ProtoMessage()    {}
func (*PutKeysRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{40}
}
func (m *PutKeysRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutKeysRequest.Unmarshal(m, b)
}
func (m *PutKeysRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutKeysRequest.Marshal(b, m, deterministic)
}
func (dst *PutKeysRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutKeysRequest.Merge(dst, src)
}
func (m *PutKeysRequest) XXX_Size() int {
	return xxx_messageInfo_PutKeysRequest.Size(m)
}
func (m *PutKeysRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutKeysRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutKeysRequest proto.InternalMessageInfo

func (m *PutKeysRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *PutKeysRequest) GetKeys() []byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type PutKeysResponse struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutKeysResponse) Reset()         { *m = PutKeysResponse{} }
func (m *PutKeysResponse) String() string { return proto.CompactTextString(m) }
func (*PutKeysResponse) ProtoMessage()    {}
func (*PutKeysResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ngobrel_1d7d43e742f3fade, []int{41}
}
func (m *PutKeysResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutKeysResponse.Unmarshal(m, b)
}
func (m *PutKeysResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutKeysResponse.Marshal(b, m, deterministic)
}
func (dst *PutKeysResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutKeysResponse.Merge(dst, src)
}
func (m *PutKeysResponse) XXX_Size() int {
	return xxx_messageInfo_PutKeysResponse.Size(m)
}
func (m *PutKeysResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutKeysResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutKeysResponse proto.InternalMessageInfo

func (m *PutKeysResponse) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*EditProfileRequest)(nil), "EditProfileRequest")
	proto.RegisterType((*EditProfileResponse)(nil), "EditProfileResponse")
	proto.RegisterType((*GetProfileRequest)(nil), "GetProfileRequest")
	proto.RegisterType((*GetProfileResponse)(nil), "GetProfileResponse")
	proto.RegisterType((*ListConversationsRequest)(nil), "ListConversationsRequest")
	proto.RegisterType((*ListConversationsResponse)(nil), "ListConversationsResponse")
	proto.RegisterType((*Conversations)(nil), "Conversations")
	proto.RegisterType((*UpdateConversationRequest)(nil), "UpdateConversationRequest")
	proto.RegisterType((*UpdateConversationResponse)(nil), "UpdateConversationResponse")
	proto.RegisterType((*DeleteContactRequest)(nil), "DeleteContactRequest")
	proto.RegisterType((*DeleteContactResponse)(nil), "DeleteContactResponse")
	proto.RegisterType((*GetContactsRequest)(nil), "GetContactsRequest")
	proto.RegisterType((*GetContactsResponse)(nil), "GetContactsResponse")
	proto.RegisterType((*Contacts)(nil), "Contacts")
	proto.RegisterType((*PutContactRequest)(nil), "PutContactRequest")
	proto.RegisterType((*PutContactResponse)(nil), "PutContactResponse")
	proto.RegisterType((*GetMessageReceptionStateRequest)(nil), "GetMessageReceptionStateRequest")
	proto.RegisterType((*GetMessageReceptionStateResponse)(nil), "GetMessageReceptionStateResponse")
	proto.RegisterType((*GetMessageStateRequest)(nil), "GetMessageStateRequest")
	proto.RegisterType((*GetMessageStateResponse)(nil), "GetMessageStateResponse")
	proto.RegisterType((*PutMessageStateRequest)(nil), "PutMessageStateRequest")
	proto.RegisterType((*PutMessageStateResponse)(nil), "PutMessageStateResponse")
	proto.RegisterType((*PutMessageReceptionStateRequest)(nil), "PutMessageReceptionStateRequest")
	proto.RegisterType((*PutMessageReceptionStateResponse)(nil), "PutMessageReceptionStateResponse")
	proto.RegisterType((*CreateConversationRequest)(nil), "CreateConversationRequest")
	proto.RegisterType((*CreateConversationResponse)(nil), "CreateConversationResponse")
	proto.RegisterType((*DeleteConversationRequest)(nil), "DeleteConversationRequest")
	proto.RegisterType((*DeleteConversationResponse)(nil), "DeleteConversationResponse")
	proto.RegisterType((*PutIntoConversationRequest)(nil), "PutIntoConversationRequest")
	proto.RegisterType((*PutIntoConversationResponse)(nil), "PutIntoConversationResponse")
	proto.RegisterType((*UploadMediaRequest)(nil), "UploadMediaRequest")
	proto.RegisterType((*UploadMediaResponse)(nil), "UploadMediaResponse")
	proto.RegisterType((*GetMediaRequest)(nil), "GetMediaRequest")
	proto.RegisterType((*GetMediaResponse)(nil), "GetMediaResponse")
	proto.RegisterType((*GetMessagesRequest)(nil), "GetMessagesRequest")
	proto.RegisterType((*GetMessagesResponseItem)(nil), "GetMessagesResponseItem")
	proto.RegisterType((*PutMessageResponse)(nil), "PutMessageResponse")
	proto.RegisterType((*PutMessageRequest)(nil), "PutMessageRequest")
	proto.RegisterType((*PublicGetKeysRequest)(nil), "PublicGetKeysRequest")
	proto.RegisterType((*PublicGetKeysResponse)(nil), "PublicGetKeysResponse")
	proto.RegisterType((*PutKeysRequest)(nil), "PutKeysRequest")
	proto.RegisterType((*PutKeysResponse)(nil), "PutKeysResponse")
	proto.RegisterEnum("ConversationType", ConversationType_name, ConversationType_value)
	proto.RegisterEnum("MessageState", MessageState_name, MessageState_value)
	proto.RegisterEnum("MessageReceptionState", MessageReceptionState_name, MessageReceptionState_value)
	proto.RegisterEnum("UploadMediaStatus", UploadMediaStatus_name, UploadMediaStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NgobrelClient is the client API for Ngobrel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NgobrelClient interface {
	// *
	// Sends message
	PutMessage(ctx context.Context, in *PutMessageRequest, opts ...grpc.CallOption) (*PutMessageResponse, error)
	// *
	// Gets messages for currently logged in deviceID
	GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (Ngobrel_GetMessagesClient, error)
	// *
	// Creates a new conversation, either a peer-to-peer or group conversation
	CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*CreateConversationResponse, error)
	// *
	// List available conversations for currently logged in userID
	ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
	// *
	// Updates a conversation
	UpdateConversation(ctx context.Context, in *UpdateConversationRequest, opts ...grpc.CallOption) (*UpdateConversationResponse, error)
	// *
	// Gets contact list of the currently logged user ID
	GetContacts(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*GetContactsResponse, error)
}

type ngobrelClient struct {
	cc *grpc.ClientConn
}

func NewNgobrelClient(cc *grpc.ClientConn) NgobrelClient {
	return &ngobrelClient{cc}
}

func (c *ngobrelClient) PutMessage(ctx context.Context, in *PutMessageRequest, opts ...grpc.CallOption) (*PutMessageResponse, error) {
	out := new(PutMessageResponse)
	err := c.cc.Invoke(ctx, "/Ngobrel/PutMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ngobrelClient) GetMessages(ctx context.Context, in *GetMessagesRequest, opts ...grpc.CallOption) (Ngobrel_GetMessagesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Ngobrel_serviceDesc.Streams[0], "/Ngobrel/GetMessages", opts...)
	if err != nil {
		return nil, err
	}
	x := &ngobrelGetMessagesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Ngobrel_GetMessagesClient interface {
	Recv() (*GetMessagesResponseItem, error)
	grpc.ClientStream
}

type ngobrelGetMessagesClient struct {
	grpc.ClientStream
}

func (x *ngobrelGetMessagesClient) Recv() (*GetMessagesResponseItem, error) {
	m := new(GetMessagesResponseItem)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ngobrelClient) CreateConversation(ctx context.Context, in *CreateConversationRequest, opts ...grpc.CallOption) (*CreateConversationResponse, error) {
	out := new(CreateConversationResponse)
	err := c.cc.Invoke(ctx, "/Ngobrel/CreateConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ngobrelClient) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	out := new(ListConversationsResponse)
	err := c.cc.Invoke(ctx, "/Ngobrel/ListConversations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ngobrelClient) UpdateConversation(ctx context.Context, in *UpdateConversationRequest, opts ...grpc.CallOption) (*UpdateConversationResponse, error) {
	out := new(UpdateConversationResponse)
	err := c.cc.Invoke(ctx, "/Ngobrel/UpdateConversation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ngobrelClient) GetContacts(ctx context.Context, in *GetContactsRequest, opts ...grpc.CallOption) (*GetContactsResponse, error) {
	out := new(GetContactsResponse)
	err := c.cc.Invoke(ctx, "/Ngobrel/GetContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NgobrelServer is the server API for Ngobrel service.
type NgobrelServer interface {
	// *
	// Sends message
	PutMessage(context.Context, *PutMessageRequest) (*PutMessageResponse, error)
	// *
	// Gets messages for currently logged in deviceID
	GetMessages(*GetMessagesRequest, Ngobrel_GetMessagesServer) error
	// *
	// Creates a new conversation, either a peer-to-peer or group conversation
	CreateConversation(context.Context, *CreateConversationRequest) (*CreateConversationResponse, error)
	// *
	// List available conversations for currently logged in userID
	ListConversations(context.Context, *ListConversationsRequest) (*ListConversationsResponse, error)
	// *
	// Updates a conversation
	UpdateConversation(context.Context, *UpdateConversationRequest) (*UpdateConversationResponse, error)
	// *
	// Gets contact list of the currently logged user ID
	GetContacts(context.Context, *GetContactsRequest) (*GetContactsResponse, error)
}

func RegisterNgobrelServer(s *grpc.Server, srv NgobrelServer) {
	s.RegisterService(&_Ngobrel_serviceDesc, srv)
}

func _Ngobrel_PutMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NgobrelServer).PutMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ngobrel/PutMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NgobrelServer).PutMessage(ctx, req.(*PutMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ngobrel_GetMessages_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetMessagesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NgobrelServer).GetMessages(m, &ngobrelGetMessagesServer{stream})
}

type Ngobrel_GetMessagesServer interface {
	Send(*GetMessagesResponseItem) error
	grpc.ServerStream
}

type ngobrelGetMessagesServer struct {
	grpc.ServerStream
}

func (x *ngobrelGetMessagesServer) Send(m *GetMessagesResponseItem) error {
	return x.ServerStream.SendMsg(m)
}

func _Ngobrel_CreateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NgobrelServer).CreateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ngobrel/CreateConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NgobrelServer).CreateConversation(ctx, req.(*CreateConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ngobrel_ListConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConversationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NgobrelServer).ListConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ngobrel/ListConversations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NgobrelServer).ListConversations(ctx, req.(*ListConversationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ngobrel_UpdateConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConversationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NgobrelServer).UpdateConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ngobrel/UpdateConversation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NgobrelServer).UpdateConversation(ctx, req.(*UpdateConversationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ngobrel_GetContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NgobrelServer).GetContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Ngobrel/GetContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NgobrelServer).GetContacts(ctx, req.(*GetContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ngobrel_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Ngobrel",
	HandlerType: (*NgobrelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutMessage",
			Handler:    _Ngobrel_PutMessage_Handler,
		},
		{
			MethodName: "CreateConversation",
			Handler:    _Ngobrel_CreateConversation_Handler,
		},
		{
			MethodName: "ListConversations",
			Handler:    _Ngobrel_ListConversations_Handler,
		},
		{
			MethodName: "UpdateConversation",
			Handler:    _Ngobrel_UpdateConversation_Handler,
		},
		{
			MethodName: "GetContacts",
			Handler:    _Ngobrel_GetContacts_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetMessages",
			Handler:       _Ngobrel_GetMessages_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ngobrel.proto",
}

func init() { proto.RegisterFile("ngobrel.proto", fileDescriptor_ngobrel_1d7d43e742f3fade) }

var fileDescriptor_ngobrel_1d7d43e742f3fade = []byte{
	// 1174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xe9, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x25, 0xf9, 0xd0, 0xd8, 0x56, 0xe8, 0xf5, 0x11, 0x9a, 0x6e, 0x11, 0x61, 0x7b, 0xc0,
	0x91, 0x0b, 0xa2, 0x70, 0x0a, 0x04, 0x28, 0xd2, 0x36, 0xa8, 0x65, 0xb8, 0x42, 0x62, 0x57, 0x90,
	0x1d, 0x14, 0x48, 0xfb, 0x67, 0x4d, 0x8e, 0x5d, 0x22, 0x12, 0xc9, 0x92, 0x2b, 0xa3, 0x7e, 0x9a,
	0xbc, 0x42, 0x5f, 0xa6, 0xef, 0x53, 0xec, 0x72, 0xc5, 0x9b, 0x91, 0x0b, 0xfb, 0x8f, 0xa0, 0x99,
	0x9d, 0x9d, 0xf9, 0x66, 0x76, 0x38, 0x07, 0x6c, 0x78, 0x37, 0xfe, 0x55, 0x88, 0x13, 0x2b, 0x08,
	0x7d, 0xee, 0x53, 0x07, 0xc8, 0x89, 0xe3, 0xf2, 0x51, 0xe8, 0x5f, 0xbb, 0x13, 0x1c, 0xe3, 0x5f,
	0x33, 0x8c, 0x38, 0x21, 0xd0, 0xf6, 0xd8, 0x14, 0x0d, 0xad, 0xa7, 0x1d, 0x74, 0xc6, 0xf2, 0x3f,
	0xd9, 0x86, 0x25, 0x9c, 0x32, 0x77, 0x62, 0x34, 0x25, 0x33, 0x26, 0xc8, 0x97, 0xb0, 0xc1, 0x6e,
	0x19, 0x67, 0xe1, 0x19, 0x3a, 0x2e, 0x1b, 0x3a, 0x46, 0x4b, 0x9e, 0xe6, 0x99, 0x74, 0x08, 0x5b,
	0x39, 0x2b, 0x51, 0xe0, 0x7b, 0x11, 0x12, 0x03, 0x56, 0xa2, 0x99, 0x6d, 0x63, 0x14, 0x49, 0x4b,
	0xab, 0xe3, 0x39, 0x29, 0x4e, 0xa6, 0x18, 0x45, 0xec, 0x06, 0x95, 0xb9, 0x39, 0x49, 0x0f, 0x61,
	0xf3, 0x14, 0x8b, 0x78, 0x77, 0x61, 0x79, 0x16, 0x61, 0x38, 0x1c, 0x28, 0xc4, 0x8a, 0x12, 0xde,
	0x65, 0x85, 0x95, 0xd9, 0xc7, 0xf6, 0xce, 0x04, 0xe3, 0xad, 0x1b, 0xf1, 0x63, 0xdf, 0xbb, 0xc5,
	0x30, 0x62, 0xdc, 0xf5, 0xbd, 0x48, 0x21, 0xa3, 0x3f, 0xc1, 0x5e, 0xc5, 0x99, 0x02, 0x42, 0xa1,
	0x3d, 0x71, 0x23, 0x6e, 0x68, 0xbd, 0xd6, 0xc1, 0xda, 0x51, 0xd7, 0xca, 0x4b, 0xc9, 0x33, 0xfa,
	0x51, 0x83, 0x8d, 0x1c, 0x5f, 0x38, 0x6b, 0xff, 0xc9, 0x78, 0xea, 0x6c, 0x4c, 0x11, 0x13, 0x56,
	0xc5, 0xbf, 0x73, 0xe1, 0x5a, 0xec, 0x45, 0x42, 0x8b, 0x78, 0xe2, 0xdf, 0x36, 0x86, 0x01, 0x57,
	0x2e, 0xcc, 0x49, 0xf2, 0x19, 0x74, 0xb8, 0x3b, 0xc5, 0x88, 0xb3, 0x69, 0x60, 0xb4, 0x7b, 0xda,
	0x41, 0x6b, 0x9c, 0x32, 0x08, 0x85, 0x75, 0xcf, 0xe7, 0xee, 0xb5, 0x6b, 0x4b, 0xe3, 0xc6, 0x92,
	0x14, 0xc8, 0xf1, 0xe8, 0x07, 0xd8, 0x7b, 0x17, 0x38, 0x8c, 0x63, 0x16, 0x66, 0xe6, 0x65, 0x2a,
	0xc1, 0x66, 0x00, 0x35, 0x3f, 0x01, 0xa8, 0x55, 0x00, 0x44, 0x47, 0x60, 0x56, 0x19, 0x7b, 0x40,
	0x42, 0x59, 0xb0, 0x3d, 0xc0, 0x09, 0x4a, 0x8d, 0x9c, 0xd9, 0x7c, 0x51, 0x4e, 0xbd, 0x81, 0x9d,
	0x82, 0xfc, 0x03, 0x8c, 0x6f, 0xcb, 0x04, 0x55, 0x9a, 0x92, 0xa4, 0xf9, 0x0e, 0xb6, 0x72, 0x5c,
	0x65, 0xe0, 0xf3, 0x5c, 0xba, 0x74, 0xac, 0x44, 0x20, 0xce, 0x94, 0xf7, 0xb0, 0x3a, 0xe7, 0x08,
	0xf0, 0x01, 0x66, 0xc1, 0xc7, 0x54, 0x92, 0xfa, 0xcd, 0x4c, 0xea, 0x17, 0xdf, 0xb8, 0x55, 0xf1,
	0xc6, 0xaf, 0x61, 0x73, 0x34, 0xe3, 0x85, 0x08, 0x1d, 0xc2, 0x9a, 0x1d, 0x73, 0x06, 0x8c, 0x33,
	0xa9, 0x33, 0x07, 0x2b, 0x7b, 0x4a, 0x7f, 0x01, 0x92, 0xd5, 0xf0, 0x80, 0x98, 0xfd, 0x06, 0xcf,
	0x4e, 0x91, 0x9f, 0xc5, 0xd4, 0x18, 0x6d, 0x0c, 0x04, 0xc4, 0x0b, 0xce, 0xf8, 0xa2, 0x7a, 0x20,
	0x72, 0x4b, 0x69, 0x19, 0x0e, 0x94, 0xda, 0x94, 0x41, 0xc7, 0xd0, 0xab, 0x57, 0xac, 0x00, 0x5b,
	0xb0, 0x1c, 0x71, 0xc6, 0x67, 0x31, 0xde, 0xee, 0xd1, 0xae, 0x55, 0x2d, 0xaf, 0xa4, 0xe8, 0x39,
	0xec, 0xa6, 0x3a, 0x1f, 0x01, 0xe3, 0x8f, 0xf0, 0xb4, 0xa4, 0x4f, 0x41, 0xfb, 0x02, 0x96, 0x84,
	0x51, 0x54, 0xc8, 0x36, 0xac, 0x9c, 0x54, 0x7c, 0x46, 0xaf, 0x61, 0x77, 0x34, 0xab, 0xc4, 0x93,
	0xb3, 0xab, 0x15, 0xec, 0x66, 0xfc, 0x6e, 0xde, 0xcb, 0xef, 0x33, 0x78, 0x5a, 0xb2, 0xf3, 0x80,
	0x37, 0xf7, 0xe1, 0x59, 0xaa, 0xae, 0xfa, 0xcd, 0x1f, 0x17, 0xff, 0x2b, 0xe8, 0xd5, 0x1b, 0x5c,
	0xe4, 0x08, 0x0d, 0x61, 0xef, 0x38, 0xc4, 0xfa, 0x92, 0x58, 0xf9, 0xf0, 0x69, 0xa9, 0x6c, 0xe6,
	0x4a, 0xe5, 0x57, 0xd0, 0xe6, 0x77, 0x01, 0xca, 0xef, 0xb2, 0x7b, 0xb4, 0x99, 0xeb, 0x12, 0x97,
	0x77, 0x01, 0x8e, 0xe5, 0x31, 0x3d, 0x07, 0xb3, 0xca, 0xa6, 0xc2, 0xfa, 0x89, 0x3a, 0x5c, 0x13,
	0xf2, 0x17, 0xb0, 0x97, 0xd4, 0xb9, 0xfb, 0x96, 0x75, 0x51, 0x9e, 0xab, 0x2e, 0x3d, 0xe0, 0xe5,
	0xff, 0x00, 0x73, 0x34, 0xe3, 0x43, 0x8f, 0xfb, 0xff, 0x27, 0x96, 0x5f, 0x43, 0xd7, 0xce, 0x88,
	0x27, 0x31, 0x2d, 0x70, 0xe9, 0x09, 0xec, 0x57, 0x6a, 0x57, 0x80, 0xcb, 0x6a, 0xb4, 0x4a, 0x35,
	0x16, 0x90, 0x77, 0xc1, 0xc4, 0x67, 0x8e, 0x1c, 0x09, 0xe6, 0xe0, 0x0c, 0x58, 0x11, 0x15, 0x10,
	0x3d, 0x2e, 0xaf, 0xad, 0x8f, 0xe7, 0x24, 0xfd, 0x1d, 0xb6, 0x72, 0xf2, 0x69, 0x7c, 0xa6, 0x72,
	0xa6, 0x98, 0xdb, 0x99, 0x93, 0xa4, 0x5f, 0x48, 0x5f, 0x62, 0x65, 0xee, 0x5f, 0xc8, 0x93, 0x24,
	0x75, 0x0f, 0xe1, 0x89, 0x2c, 0x11, 0x79, 0x24, 0xd5, 0x8a, 0xe9, 0x37, 0xa0, 0xa7, 0xc2, 0x29,
	0x8c, 0x1a, 0xdc, 0x71, 0xbb, 0x52, 0x5f, 0x45, 0xd2, 0xae, 0x3e, 0x36, 0xb3, 0x45, 0x29, 0xe9,
	0x57, 0x43, 0x8e, 0x53, 0xd2, 0x83, 0xb5, 0x10, 0x6d, 0x37, 0x70, 0xd1, 0x4b, 0xb3, 0x25, 0xcb,
	0x12, 0x63, 0x4b, 0x84, 0x9e, 0x23, 0x1f, 0x51, 0x8d, 0x2d, 0x73, 0x5a, 0xc4, 0x3f, 0xfe, 0x3f,
	0xc0, 0x5b, 0xd7, 0x16, 0x1f, 0x76, 0x3c, 0xbd, 0x14, 0xb8, 0xf9, 0x6f, 0x5f, 0x0d, 0x31, 0xe9,
	0xb7, 0xdf, 0x07, 0x5d, 0x11, 0x97, 0xc9, 0x60, 0x11, 0x0f, 0x32, 0x25, 0x3e, 0x39, 0x80, 0x27,
	0x8a, 0x77, 0x1c, 0xfb, 0x1c, 0x19, 0xcb, 0xd2, 0x64, 0x91, 0x9d, 0xd1, 0x7a, 0xe2, 0xd9, 0xe1,
	0x5d, 0xc0, 0xd1, 0x31, 0x56, 0x64, 0x56, 0x97, 0xf8, 0xf4, 0x48, 0x36, 0xbf, 0xa4, 0x9a, 0xa8,
	0x38, 0x97, 0x2a, 0x56, 0x16, 0x35, 0xfd, 0x57, 0x93, 0x3d, 0x37, 0xb9, 0x14, 0xbf, 0xe4, 0xe2,
	0x78, 0x96, 0xfa, 0xc7, 0xc2, 0x58, 0xb4, 0xee, 0x1f, 0x8b, 0xf6, 0xfd, 0x63, 0xb1, 0x54, 0x13,
	0x0b, 0x0b, 0xb6, 0x47, 0xb3, 0xab, 0x89, 0x6b, 0x9f, 0x22, 0x7f, 0x83, 0x77, 0xd1, 0xa2, 0x79,
	0xeb, 0x10, 0x76, 0x0a, 0xf2, 0xe9, 0x18, 0xff, 0x01, 0xef, 0x22, 0x95, 0xa3, 0xf2, 0x3f, 0x7d,
	0x05, 0xdd, 0xd1, 0xec, 0x3e, 0x6a, 0x93, 0xdb, 0xcd, 0xcc, 0xed, 0xe7, 0xf0, 0x24, 0xb9, 0x9d,
	0xd6, 0xcd, 0xaa, 0xeb, 0xfd, 0x1f, 0x40, 0x2f, 0xd6, 0x61, 0xd2, 0x05, 0x18, 0x21, 0x86, 0x97,
	0xbe, 0xf8, 0xd5, 0x1b, 0xa4, 0x03, 0x4b, 0xa7, 0xa1, 0x3f, 0x0b, 0x74, 0x4d, 0x1c, 0x9d, 0x31,
	0x8f, 0xdd, 0xe0, 0x14, 0x3d, 0xae, 0x37, 0xfb, 0xcf, 0x61, 0x3d, 0xdb, 0x1b, 0x09, 0xc0, 0xf2,
	0xb9, 0x1f, 0x4e, 0xd9, 0x44, 0x6f, 0x90, 0x0d, 0xe8, 0x8c, 0x91, 0x87, 0xcc, 0xe6, 0xe8, 0xe8,
	0x5a, 0x7f, 0x00, 0x3b, 0x95, 0x6d, 0x48, 0xa8, 0x1f, 0x84, 0xec, 0x9a, 0xeb, 0x0d, 0xb2, 0x0a,
	0xed, 0x0b, 0xa1, 0x58, 0x23, 0xeb, 0xb0, 0x2a, 0xc4, 0xdc, 0x5b, 0x74, 0xf4, 0xa6, 0xe0, 0x8f,
	0x91, 0x39, 0x7a, 0xab, 0xff, 0x12, 0x36, 0x4b, 0x15, 0x43, 0x58, 0x8a, 0x99, 0xae, 0x77, 0x13,
	0x6b, 0x19, 0xf8, 0x1e, 0xea, 0x9a, 0x50, 0x7d, 0x12, 0x86, 0x7e, 0xa8, 0x37, 0x8f, 0xfe, 0x69,
	0xc1, 0xca, 0x79, 0xbc, 0x32, 0x92, 0x97, 0x00, 0x69, 0x46, 0x12, 0x62, 0x95, 0xd2, 0xd3, 0xdc,
	0xb2, 0xca, 0x79, 0x4e, 0x1b, 0xe4, 0x35, 0xac, 0x65, 0x0a, 0x04, 0xd9, 0xb2, 0xca, 0x55, 0xc4,
	0x34, 0xac, 0x9a, 0x1a, 0x42, 0x1b, 0xdf, 0x6a, 0xe4, 0x57, 0x20, 0xe5, 0xee, 0x46, 0x4c, 0xab,
	0xb6, 0xcd, 0x9a, 0xfb, 0x56, 0x7d, 0x3b, 0xa4, 0x0d, 0xf2, 0x16, 0x36, 0x4b, 0x8b, 0x19, 0xd9,
	0xb3, 0xea, 0x16, 0x39, 0xd3, 0xb4, 0x6a, 0xf7, 0x38, 0xda, 0x10, 0xf0, 0xca, 0x6b, 0x09, 0x31,
	0xad, 0xda, 0xc5, 0xc8, 0xdc, 0xb7, 0xea, 0xf7, 0x18, 0xda, 0x20, 0xdf, 0xcb, 0x88, 0x25, 0xf3,
	0xbc, 0x8c, 0x58, 0x61, 0x4d, 0x30, 0xb7, 0xad, 0x8a, 0x2d, 0x81, 0x36, 0x7e, 0xee, 0xbc, 0x5f,
	0x51, 0x4b, 0xfe, 0xd5, 0xb2, 0xdc, 0xf2, 0x5f, 0xfc, 0x17, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x4c,
	0x65, 0x21, 0xf6, 0x0f, 0x00, 0x00,
}
