version: '3.1'
services:
  build:
    image: golang:1.11beta2-alpine
    environment:
      GO111MODULE: "on"
    volumes:
      - ..:/go/src
    command: >
      sh -c "apk update && apk add git gcc musl-dev docker
      && docker login registry.gitlab.com
      && cd /go/src && go mod -sync && go test"
