version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: omama
     # PGDATA: /data
    volumes:
     # - /home/mdamt/data/psql:/data
      - ../deploy:/deploy
      - ../deploy/settings.sh:/docker-entrypoint-initdb.d/settings.sh
      - ./init-user.sh:/docker-entrypoint-initdb.d/init-user.sh
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

